### ISSUE TITLE
Unrecognized option: -d64

### ISSUE THREAD

**Issue by 9527567** [andzajan/mzmatch.R#3]
This is a nice project, but I encountered a small problem when I installed PeakML.Viewer(). I think this is the problem that the new version of Java no longer has the - d64 option. So what should I do？  Using the older java version or  a newer version of the PeakML.Viewer are available?

![2020-11-17_11-14](https://user-images.githubusercontent.com/50236967/99342101-12dc5f80-28c6-11eb-9760-499466996df1.png)

**Comment by andzajan** [comment]
One of the solutions would be to find parameters what are needed for new java and amend script in the link below.
Or ineed to use Java 7 on which this code was last time tested.

https://github.com/andzajan/mzmatch.R/blob/master/R/PeakML.Viewer.R#L90-L100

**Comment by 9527567** [comment]
Thank you very much! So do you mind if I submit PR?

**Comment by andzajan** [comment]
Thank you, I would really appreaciate it.
In case the old jar file doesn't work with new Java version, I could try to compile a new binary.

**Comment by 9527567** [comment]
That's great. Thank you again for your reply！
