### ISSUE TITLE
Not able to run PeakML

### ISSUE THREAD

**Issue by maximiliaoO** [andzajan/mzmatch.R#8]
Hi,
I tried to follow the mzMatch/PeakML tutorial (http://mzmatch.sourceforge.net/tutorial.mzmatch.r.advanced.php), but I am not able to run PeakML. When I run
`PeakML.Viewer()`

I get

> OS type: x86_64-apple-darwin17.0 
> arguments 'show.output.on.console', 'minimized' and 'invisible' are for Windows only
> 2022-01-16 14:09:23.372 java[1857:23423] *** WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
> Exception in thread "main" org.eclipse.swt.SWTError: Not implemented (java.lang.ClassNotFoundException: apple.awt.CEmbeddedFrame)
> 	at org.eclipse.swt.SWT.error(Unknown Source)
> 	at org.eclipse.swt.SWT.error(Unknown Source)
> 	at org.eclipse.swt.awt.SWT_AWT.new_Frame(Unknown Source)
> 	at peakmlviewer.widgets.MoleculePanel.<init>(MoleculePanel.java:68)
> 	at peakmlviewer.view.IdentificationView.<init>(IdentificationView.java:100)
> 	at peakmlviewer.MainWnd.<init>(MainWnd.java:140)
> 	at peakmlviewer.PeakMLViewer.main(PeakMLViewer.java:44)
> Caused by: java.lang.ClassNotFoundException: apple.awt.CEmbeddedFrame
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:467)
> 	... 5 more

I am running MacOS Monterey 12.1, RStudio 1.4.1717 and updated Java to the latest version. I also downloaded and tried to run the PeakML.Viewer.jar file but I get a similar error:

> ***WARNING: Display must be created on main thread due to Cocoa restrictions.
> Exception in thread "main" org.eclipse.swt.SWTException: Invalid thread access
> 	at org.eclipse.swt.SWT.error(Unknown Source)
> 	at org.eclipse.swt.SWT.error(Unknown Source)
> 	at org.eclipse.swt.SWT.error(Unknown Source)
> 	at org.eclipse.swt.widgets.Display.error(Unknown Source)
> 	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
> 	at org.eclipse.swt.widgets.Display.create(Unknown Source)
> 	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
> 	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
> 	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
> 	at peakmlviewer.MainWnd.<init>(MainWnd.java:57)
> 	at peakmlviewer.PeakMLViewer.main(PeakMLViewer.java:44)

I am very much a beginner in R and have no knowledge of Java, so I am not quite sure how to diagnose this. Is this an issue with newer versions of Java or my OS?
Thanks for your help!

**Comment by andzajan** [comment]
Hi @maximiliaoO, it looks like changes in the latest Java don't support our relatively old codebase. Would it be possible for you to downgrage to Java 15 and try again?

EDIT. It looks like it's Mac specific problem, we have tested code on Windows and Linux with Java 15. On Mac OS you probably can try to use Java older than 10.7.

**Comment by maximiliaoO** [comment]
Thanks for your help @andzajan. I downgraded Java to 9.0.4 which solved the problem.
