### ISSUE TITLE
 PeakML.xcms.write.SingleMeasurement Java error

### ISSUE THREAD

**Issue by chaesh90** [andzajan/mzmatch.R#9]
I thought I solved this by reinstalling rJava and mzmatch.r, but it happened again after restarting R studio.

----------------------------------------------------------------------------------------------------------------------------------------

Hello, I'm fairly new to R and mzmatch so this might be a rookie mistake.

When I follow your instruction and run the code, xcmsSet seems to work fine but in  PeakML.xcms.write.SingleMeasurement function,
this happens.

![image](https://github.com/andzajan/mzmatch.R/assets/145546263/25cf29d7-24e6-4352-9030-eca8162631e9)

I have installed JAVA 15 SE as you suggested.

Please help soon.

Thanks.

**Comment by chaesh90** [comment]
Sorry, I reinstalled mzmatch and it solved!

**Comment by andzajan** [comment]
Hi, can I just confirm that you packages are stored on local drive and not on some remote drive where by default many University setups will store user data?

In that case you can overcome problem by running `mzmatch.init(version.1=FALSE)` every time you star Rstudio session.

**Comment by chaesh90** [comment]
Hi, and thanks for the fast response. Here is the location of packages,
![image](https://github.com/andzajan/mzmatch.R/assets/145546263/32ac03de-f48e-41d5-ab83-7d6f1b77285e)

and here is the code I ran which includes 'mzmatch.init(versioin.1=FALSE)'.
![image](https://github.com/andzajan/mzmatch.R/assets/145546263/47fe4d9c-6d59-49ae-bace-9c46f172eee2)

**Comment by andzajan** [comment]
Hi, I had a look, it looks like download or the mzmatch Java files is not completing properly for some reason.

Can you please download this file manually from here: 
https://sourceforge.net/projects/mzmatch/files/mzmatch.R/mzmatch_2.0.jar/download

And replace it with one you have in `mzmatch.R` folder.
![image](https://github.com/andzajan/mzmatch.R/assets/10488638/d3148498-b80a-48e4-ad74-6dae609f08eb)

Then `mzmatch.init(version.1=FALSE)` should initialise with correct and full java file.

I will have a look if I can fix this permanently, but in general mzmatch package hasn't been supported for quite a while now.

**Comment by chaesh90** [comment]
It's finally working now, Thanks.

I have few more questions, but I'll open new issues for those seperately.

Thanks again!
